export const FETCH_CHANNELS = 'FETCH_CHANNELS';
export const CHANNEL_LOADING = 'CHANNEL_LOADING';
export const CHANNEL_FAILED = 'CHANNEL_FAILED';

export const SINGLE_CHANNEL = 'SINGLE_CHANNEL';
export const SINGLE_LOADING = 'SINGLE_LOADING';
export const SINGLE_FAILED = 'SINGLE_FAILED';

export const GET_PROGRAMS = 'GET_PROGRAMS';
export const PROGRAMS_LOADING = 'PROGRAMS_LOADING';
export const PROGRAMS_FAILED = 'PROGRAMS_FAILED';
